= Transactions in distributed systems

Distributed systems are becoming the default way of developing Java applications. When individual parts of the system pass messages through the network, we must expect that some communication can fail. As defined by the CAP theorem, we must then make a design choice between the consistency and availability of the developed system. Traditional ACID transactions in the distributed system are problematic as the locking of resources required for consistency might cause the blocking of valid user requests because of the consistency protocol communication failures. Alternative BASE transactions based on the saga pattern focus on the availability of system resources at a tradeoff provided by the eventual consistency guarantee. However, network failures can still cause major problems. 

In this talk, we look at the difference between ACID and BASE approaches to distributed transactions. We explain and compare both architectures, highlighting their benefits and drawbacks. Then, we compare both solutions through live coded demos implemented with the Narayana transaction manager - REST AT for atomic ACID transactions based on 2PC protocol and saga-based MicroProfile LRA for long-running BASE actions. After the talk, you can decide which solution suits your distributed transactional systems better.
