= Transactions recovery in distributed systems

Distributed systems are becoming the default way of developing Java applications. When individual parts of the system pass messages through the network, we must expect that some communication can fail. Partition tolerance is definitely essential but very hard to achieve. As defined by the CAP theorem, we are then required to make a design choice between the consistency and availability of the developed system. Traditional ACID transactions in the distributed system can thus be problematic as the locking of resources required for consistency might cause the blocking of valid user requests just because the consistency protocol communication fails. Alternative BASE transactions based on the saga pattern provide only the eventual consistency guarantee with a focus on the availability of system resources. However, that also doesn't mean that the network failures don't need to be accounted for. This talk explains the difference between ACID and BASE approaches to distribution transactions regarding network failures and service recovery. We look into both solutions implemented with the Narayana transaction manager - REST AT for atomic ACID transactions based on 2PC protocol and saga-based MicroProfile LRA for long-running BASE actions.
