= Transactions recovery in distributed systems

Distributed systems are becoming the default way of developing Java applications. When individual parts of the system pass messages through the network, we must expect that some communication can fail. Partition tolerance is definitely very hard to achieve. As defined by the CAP theorem, we are then required to make a design choice between the consistency and availability of the developed system. Traditional ACID transactions in the distributed system can thus be problematic as the locking of resources required for consistency might cause the blocking of valid user requests just because of the consistency protocol communication failures. Alternative BASE transactions based on the saga pattern focus on the availability of system resources at a tradeoff provided by the eventual consistency guarantee. However, that also doesn't mean that the network failures don't need to be accounted for. This talk explains the difference between ACID and BASE approaches to distributed transactions regarding network failures and service recovery. We look into both solutions through live coded demos implemented with the Narayana transaction manager - REST AT for atomic ACID transactions based on 2PC protocol and saga-based MicroProfile LRA for long-running BASE actions.
