= The well-earned rest from REST

Very often, our applications need to communicate with the outside world. Whether we talk with other services in the same system, with some external provider, or of course, with the customers, we need to choose the communication protocol that both sides agree on. Representational State Transfer (REST) architectural style, on top of the well-understood HTTP protocol, is unarguably one of the first choices that we look into as the industry has a lot of expertise in this area. However, there are other alternatives that provide interesting distinctive features that might be better suited for the same scenarios. In this talk, we focus on the two that are most similar to REST development, namely GraphQL -- a query language that allows us to request only the data that we really need, and gRPC -- a low latency communication framework based on binary payload. We will implement both server and client applications in Java on top of the Quarkus framework to demonstrate how these technologies differ and what benefits they can provide in your applications. Altogether, we will have a while to get that well-deserved rest from REST.
