= Building reactive microservices with MicroProfile

Modern microservices applications need to be able to adjust to change. It doesn't matter whether these changes concern functional requirements, fluctuating load, or more frequently network and service failures. The system should be able to remain responsive in every situation as defined in the Reactive Manifesto. The reactive programming has recently become a popular programming paradigm. In the Java world, there are already a few options the users can choose from when creating reactive applications like Reactive eXtensions or Reactive Streams. In this session, we will introduce a new set of APIs created under Eclipse MicroProfile called the MicroProfile Reactive Streams Operators (the manipulation of Reactive Streams) and the MicroProfile Reactive Messaging (the development model that allows CDI beans to produce, consume, and process messages) together with the rationale why they are needed in the MicroProfile portfolio and a practical live coded demonstration. 
