= A day in the life of a Quarkus developer

You've probably already heard about Quarkus if you are a Java developer. You heard about the developer joy that is integral for Quarkus to provide. But what is it really? How does it help you with your day-to-day tasks? What benefits, shortcuts, or just general benefits it brings to your work? In this talk, we answer these questions. In this purely live-coded session, we create a new Quarkus project and show you how to jump-start your Java microservices with many different features that Quarkus brings out of the box. We will make it interactive, so if there is something that you want to see, we will demonstrate it. But in general, we aim to show typical user application development with a database, remote connections based on blocking and asynchronous APIs, and security. Of course, we can't leave out packaging into containers and their deployment to OpenShift. Quarkus is a framework that makes the developer productivity (and the mentioned joy that comes with it) a requirement. You will see what we can create with Quarkus in the provided time. And then you will understand what Quarkus development joy is.
