= Rocking Java microservices with Quarkus

== The getting started experience

Java has a generally bad name when it comes to its usage in the current fast moving world of containers, Kubernetes, microservices and serverless because of its boot times and memory footprints. However, this is no longer true with Quarkus -- a framework tailored for GraalVM and OpenJDK HotSpot which allows you to create Java applications that are ready for cloud while you can still utilize your knowledge of well known Java frameworks and standards like JAX-RS, CDI, JPA / Hibernate, Eclipse MicroProfile and much more. In this truly slideless live coding session we will explore the development with Quarkus from scratch covering creating and packaging of your Quarkus application, demonstrating the power of live reload mode, and introducing simplified ORM with the Panache framework. Come to see how your Java application can start serving client requests in a number of milliseconds while still utilizing only a few MB of RAM.

