= Steps

== First demo app -- plugin, live reload, reactive

* Create new project

`mvn io.quarkus:quarkus-maven-plugin:0.12.0:create`

* live reload 

** change hello message

** add config property for message
// add front end reload also? 

** refresh in browser or curl

* run test, fix test

* list extensions
`mvn quarkus:list-extensions`

** add extensions JSON-B, reactive streams operators
`mvn quarkus:add-extension -Dextensions="quarkus-resteasy-jsonb"`

** add Planet JSON, name, diameter, climate

* reactive

** add reactive streams operators
`mvn quarkus:add-extension -Dextensions="io.quarkus:quarkus-smallrye-reactive-streams-operators"`

** add endpoint with ReactiveStreams.of(message)

** add endpoint with supplyAsync

** add PublisherBean with SSE

* native build


== Openshift deployment

* login
`oc login`

* new project
`oc new-project quarkus --display-name="Sample Quarkus App"`

* new build
`oc new-build quay.io/redhat/ubi-quarkus-native-runner --binary --name=quarkus-quickstart -l app=quarkus-quickstart`

`oc start-build quarkus-quickstart --from-file=target/getting-started-1.0-SNAPSHOT-runner --follow`

* new app
`oc new-app quarkus-quickstart`

`oc expose service quarkus-quickstart`

`oc rollout status -w dc/quarkus-quickstart`

* scale up
`oc scale --replicas=10 dc/quarkus-quickstart`

== Panache

* create new project 

* add extensions
`mvn quarkus:add-extension -Dextensions="io.quarkus:quarkus-resteasy-jsonb,io.quarkus:quarkus-hibernate-orm-panache,io.quarkus:quarkus-jdbc-postgresql"`

* show default endpoint is working

* add connection properties
----
quarkus.datasource.url=jdbc:postgresql://localhost:5432/avenger
quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.username=developer
quarkus.datasource.password=developer
quarkus.hibernate-orm.database.generation=drop-and-create
----

* add Avenger entity (name, civilName, snapped)

* add @Column annotation to change civilName to real_name

* rewrite default endpoint to listAll()

* add post method for /avenger taking JsonObject

* add import.sql to resources folder
----
INSERT INTO avenger(id, name, real_name, snapped) VALUES (nextval('hibernate_sequence'), 'Iron Man', 'Tony Stark', FALSE)
INSERT INTO avenger(id, name, real_name, snapped) VALUES (nextval('hibernate_sequence'), 'Captain America', 'Steve Rogers', FALSE)
INSERT INTO avenger(id, name, real_name, snapped) VALUES (nextval('hibernate_sequence'), 'Black Widow', 'Natasha Romanoff', FALSE)
INSERT INTO avenger(id, name, real_name, snapped) VALUES (nextval('hibernate_sequence'), 'Spider-Man', 'Peter Parker', TRUE)
INSERT INTO avenger(id, name, real_name, snapped) VALUES (nextval('hibernate_sequence'), 'Hulk', 'Bruce Banner', FALSE)
INSERT INTO avenger(id, name, real_name, snapped) VALUES (nextval('hibernate_sequence'), 'Groot', 'I am Groot!', TRUE)
----

* queries - add endpoint for

** find by id at \{id}
*** show setter getter in DB

** find by snapped at \unsnapped

** search at /search/{search}
`return Avenger.list("name like :search", Parameters.with("search", "%" + search + "%"));`

** order at \ordered
`return Avenger.list("order by real_name");`
`return Avenger.listAll(Sort.by("real_name"));`
`return Avenger.list("snapped", Sort.by("real_name"), false);`

** stream at \space
`return Avenger.list("name like '% %'");`
----
return Avenger.<Avenger>streamAll()
            .filter(a -> a.name.contains(" "))
            .limit(1)
            .collect(Collectors.toList());
----

* add datatable
** add endpoint
----
@GET
    @Path("/datatable")
    @Produces(MediaType.APPLICATION_JSON)
    public DataTable datatable(
        @QueryParam("draw") int draw,
        @QueryParam("start") int start,
        @QueryParam("length") int length,
        @QueryParam("search[value]") String searchVal) {
----

** add result json object
----
public class DataTable {

    private long draw;
    private long recordsTotal;
    private long recordsFiltered;
    private List<Avenger> data;
    private String error;

----

** implement resource method

----
DataTable result = new DataTable();
result.setDraw(draw);

if (searchVal != null && !searchVal.isEmpty()) {
            filteredAvengers = Avenger.searchByName(searchVal);
        } else {
            filteredAvengers = Avenger.findAll();
        }
----

where 

----
return Avenger.find("name like :search or real_name like :search", 
            Parameters.with("search", "%" + searchValue + "%"));
----

paging
----
int page_num = start / length;
filteredAvengers.page(page_num, length);
----

rest
----
result.setRecordsFiltered(filteredAvengers.count());
result.setData(filteredAvengers.list());
result.setRecordsTotal(Avenger.count());

return result;

----

* test endpoint
`http ":8080/avenger/datatable?draw=1&start=0&length=10&search[value]=e"`

* add fake avengers
** add avenger name generator
** add startup observer
----
@Transactional
    public void observeStart(@Observes StartupEvent event) {
        for (int i = 0; i < 10000; i++) {
            String name = AvengerNameGenerator.generateName();

            Avenger avenger = new Avenger();
            avenger.name = name;
            avenger.civilName = "Fake";
            avenger.snapped = true;

            avenger.persist();
        }
    }
----

* add html


== Additional stuff
----
@Id
@SequenceGenerator(
          name = "personSequence",
          sequenceName = "person_id_seq",
          allocationSize = 1,
          initialValue = 4)
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "personSequence")
public Integer id;
----

* add io.quarkus:quarkus-smallrye-reactive-messaging extension

----
@Inject
    @Stream("fake-avengers")
    Emitter<String> fakeAvengers;

@POST
    @Path("addFake")
    public String createFakeAvenger() {
        String name = AvengerNameGenerator.generateName();
        
        CompletableFuture.supplyAsync(() -> {
            fakeAvengers.send(name);
            
            return name;
        }).whenComplete((s, e) -> System.out.println(s));

        return name;
    }
----

AvengerProcessor

----
	@Inject
    AvengerGenerator avengerGenerator;
    
    @Incoming("fake-avengers")
    @Outgoing("processed-avengers")
    @Broadcast
    @Transactional
    public String process(String avengerName) {
        Avenger avenger = avengerGenerator.createFakeAvenger("Mighty " + avengerName);
        
        avenger.persist();

        return avenger.name;
    }
----

basic publisher 
----
    @Inject
    @Stream("processed-avengers")
    Publisher<String> processedAvengers;
    
    @GET
    @Path("stream")
    @Produces(MediaType.SERVER_SENT_EVENTS)
    public Publisher<String> publisher() {
        return processedAvengers;
    }
----

----
@Inject
    DataTableSocket dataTableSocket;
    
    @Incoming("processed-avengers")
    public void dataTableUpdate(String avengerName) {
        dataTableSocket.broadcast(avengerName);
    }

    @Incoming("processed-avengers")
    public void avengerProcessor(String avengerName) {
        System.out.println("Processed " + avengerName);
    }
----

After above is working successfully

change type of messages to Message<String> and Message<Avenger>

----
public Message<Avenger> process(Message<String> avengerName) {
        Avenger avenger = avengerGenerator.createFakeAvenger("Mighty " + avengerName.getPayload());
        
        avenger.persist();

        return Message.of(avenger);
    }
----

----
@Incoming("processed-avengers")
    public CompletionStage<Message<Void>> dataTableUpdate(Message<Avenger> avenger) {
        return CompletableFuture.runAsync(() -> dataTableSocket.broadcast(avenger.getPayload().name))
            .thenApply(Message::of);
    }
----

Add kafka connector

copy docker-compose.yaml for kafka

mvn quarkus:add-extension -Dextensions="quarkus-smallrye-reactive-messaging-kafka"

copy properties from sample project 

----
smallrye.messaging.sink.fake-avengers.type=io.smallrye.reactive.messaging.kafka.Kafka
smallrye.messaging.sink.fake-avengers.topic=fake-avengers
smallrye.messaging.sink.fake-avengers.bootstrap.servers=localhost:9092
smallrye.messaging.sink.fake-avengers.key.serializer=org.apache.kafka.common.serialization.StringSerializer
smallrye.messaging.sink.fake-avengers.value.serializer=org.apache.kafka.common.serialization.StringSerializer
smallrye.messaging.sink.fake-avengers.acks=1
        
smallrye.messaging.source.fake-avengers-kafka.type=io.smallrye.reactive.messaging.kafka.Kafka
smallrye.messaging.source.fake-avengers-kafka.topic=fake-avengers
smallrye.messaging.source.fake-avengers-kafka.bootstrap.servers=localhost:9092
smallrye.messaging.source.fake-avengers-kafka.key.deserializer=org.apache.kafka.common.serializati`on.StringDeserializer
smallrye.messaging.source.fake-avengers-kafka.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
smallrye.messaging.source.fake-avengers-kafka.group.id=my-group-id
----


