= Steps

== First demo app -- plugin, live reload, reactive

* Create new project

`mvn io.quarkus:quarkus-maven-plugin:0.12.0:create`

* live reload 

** change hello message

** add config property for message
// add front end reload also? 

** refresh in browser or curl

* run test, fix test

* list extensions
`mvn quarkus:list-extensions`

** add extensions JSON-B, reactive streams operators
`mvn quarkus:add-extension -Dextensions="quarkus-resteasy-jsonb"`

** add Planet JSON, name, diameter, climate

* reactive

** add reactive streams operators
`mvn quarkus:add-extension -Dextensions="io.quarkus:quarkus-smallrye-reactive-streams-operators"`

** add endpoint with ReactiveStreams.of(message)

** add endpoint with supplyAsync

** add PublisherBean with SSE

* native build


== Openshift deployment

* login
`oc login`

* new project
`oc new-project quarkus --display-name="Sample Quarkus App"`

* new build
`oc new-build quay.io/redhat/ubi-quarkus-native-runner --binary --name=quarkus-quickstart -l app=quarkus-quickstart`

`oc start-build quarkus-quickstart --from-file=target/getting-started-1.0-SNAPSHOT-runner --follow`

* new app
`oc new-app quarkus-quickstart`

`oc expose service quarkus-quickstart`

`oc rollout status -w dc/quarkus-quickstart`

* scale up
`oc scale --replicas=10 dc/quarkus-quickstart`

== Panache

* create new project 

* add extensions
`mvn quarkus:add-extension -Dextensions="io.quarkus:quarkus-resteasy-jsonb,io.quarkus:quarkus-hibernate-orm-panache,io.quarkus:quarkus-jdbc-postgresql"`

* show default endpoint is working

* add connection properties
----
quarkus.datasource.url=jdbc:postgresql://localhost:5432/avenger
quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.username=developer
quarkus.datasource.password=developer
quarkus.hibernate-orm.database.generation=drop-and-create
----

* add Avenger entity (name, civilName, snapped)

* rewrite default endpoint to listAll()

* add post method for /avenger taking JsonObject

* add import.sql to resources folder
----
INSERT INTO avenger(id, name, real_name, snapped) VALUES (nextval('hibernate_sequence'), 'Iron Man', 'Tony Stark', FALSE)
INSERT INTO avenger(id, name, real_name, snapped) VALUES (nextval('hibernate_sequence'), 'Captain America', 'Steve Rogers', FALSE)
INSERT INTO avenger(id, name, real_name, snapped) VALUES (nextval('hibernate_sequence'), 'Black Widow', 'Natasha Romanoff', FALSE)
INSERT INTO avenger(id, name, real_name, snapped) VALUES (nextval('hibernate_sequence'), 'Spider-Man', 'Peter Parker', TRUE)
INSERT INTO avenger(id, name, real_name, snapped) VALUES (nextval('hibernate_sequence'), 'Hulk', 'Bruce Banner', FALSE)
INSERT INTO avenger(id, name, real_name, snapped) VALUES (nextval('hibernate_sequence'), 'Groot', 'I am Groot!', TRUE)
----

* queries - add endpoint for

** find by id at \{id}
*** show setter getter in DB

** find by snapped at \unsnapped

** search at /search/{search}
`return Avenger.list("name like :search", Parameters.with("search", "%" + search + "%"));`

** order at \ordered
`return Avenger.list("order by real_name");`
`return Avenger.listAll(Sort.by("real_name"));`
`return Avenger.list("snapped", Sort.by("real_name"), false);`

** stream at \space
`return Avenger.list("name like '% %'");`
----
return Avenger.<Avenger>streamAll()
            .filter(a -> a.name.contains(" "))
            .limit(1)
            .collect(Collectors.toList());
----

* add datatable
** add endpoint
----
@GET
    @Path("/datatable")
    @Produces(MediaType.APPLICATION_JSON)
    public DataTable datatable(
        @QueryParam("draw") int draw,
        @QueryParam("start") int start,
        @QueryParam("length") int length,
        @QueryParam("search[value]") String searchVal) {
----

** add result json object
----
public class DataTable {

    public long draw;
    public long recordsTotal;
    public long recordsFiltered;
    public List<Avenger> data;
    public String error;

----

** implement resource method

----
DataTable result = new DataTable();
result.setDraw(draw);

if (searchVal != null && !searchVal.isEmpty()) {
            filteredAvengers = Avenger.searchByName(searchVal);
        } else {
            filteredAvengers = Avenger.findAll();
        }
----

where 

----
return Avenger.find("name like :search or real_name like :search", 
            Parameters.with("search", "%" + searchValue + "%"));
----

paging
----
int page_num = start / length;
filteredAvengers.page(page_num, length);
----

rest
----
result.setRecordsFiltered(filteredAvengers.count());
result.setData(filteredAvengers.list());
result.setRecordsTotal(Avenger.count());

return result;

----

* test endpoint
`http ":8080/avenger/datatable?draw=1&start=0&length=10&search[value]=e"`

* add fake avengers
** add avenger name generator
** add startup observer
----
@Transactional
    public void observeStart(@Observes StartupEvent event) {
        for (int i = 0; i < 10000; i++) {
            String name = AvengerNameGenerator.generateName();

            Avenger avenger = new Avenger();
            avenger.name = name;
            avenger.civilName = "Fake";
            avenger.snapped = true;

            avenger.persist();
        }
    }
----

* add html


== Additional stuff
----
@Id
@SequenceGenerator(
          name = "personSequence",
          sequenceName = "person_id_seq",
          allocationSize = 1,
          initialValue = 4)
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "personSequence")
public Integer id;
----
